version: '3'

services:
  db:
    image: postgres:16
    container_name: postgre_padelplanet
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      POSTGRES_INITDB_WALDIR: ${POSTGRES_INITDB_WALDIR}
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./db/wal:/wal
    command: ["postgres", "-c", "max_connections=200"]